- name: "Get file stats of default browse history db at '{{ qutebrowser_default_browse_history_db_path }}'"
  ansible.builtin.stat:
    path: "{{ qutebrowser_default_browse_history_db_path }}"
  register: default_db_stats

- name: "Get file stats of saved browse history db at '{{ qutebrowser_try_link_to_saved_history_db_path }}'"
  ansible.builtin.stat:
    path: "{{ qutebrowser_try_link_to_saved_history_db_path }}"
  register: saved_db_stats

- name: "Before symlinking to saved db, make backup copy of default db '{{ qutebrowser_default_browse_history_db_path }}'"
  ansible.builtin.copy:
    src: "{{ qutebrowser_default_browse_history_db_path }}"
    dest: "{{ qutebrowser_default_browse_history_db_path }}.ansible_bkup"
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '0644'
  become: true
  become_user: root
  when: (default_db_stats.stat.exists) and
        (not default_db_stats.stat.islnk) and
        (saved_db_stats.stat.exists)

- name: "Symlink default db '{{ qutebrowser_default_browse_history_db_path }}' to saved db '{{ qutebrowser_try_link_to_saved_history_db_path }}'"
  ansible.builtin.file:
    src: "{{ qutebrowser_try_link_to_saved_history_db_path }}"
    dest: "{{ qutebrowser_default_browse_history_db_path }}"
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '0644'
    state: link
  become: true
  become_user: root
  when: saved_db_stats.stat.exists

