- name: "Create user qutebrowser config dir at '{{ qutebrowser_user_config_dir }}'"
  ansible.builtin.file:
    path: "{{ qutebrowser_user_config_dir }}"
    state: directory
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Create user qutebrowser cache dir at '{{ cache_dir }}'"
  ansible.builtin.file:
    path: "{{ cache_dir }}"
    state: directory
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '755'
  vars:
    cache_dir: "{{ qutebrowser_user_browse_history_db_path | ansible.builtin.dirname }}"
  become: true
  become_user: root

