- name: "Create qutebrowser user config dirs"
  ansible.builtin.include_tasks: dirs.yml

- name: "Configure main qutebrowser settings, and set up quickmarks file"
  ansible.builtin.include_tasks: settings_and_quickmarks.yml

- name: "Try to set up a link to existing user browse history database file"
  ansible.builtin.include_tasks: browse_history.yml

