- name: "Configure user qutebrowser settings in '{{ qutebrowser_user_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ qutebrowser_user_config_file_path }}"
    src: "config_py.j2"
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '644'
    force: yes
  become: true
  become_user: root

- name: "Configure user qutebrowser quickmark urls in '{{ qutebrowser_quickmarks_file_path }}'"
  ansible.builtin.template:
    dest: "{{ qutebrowser_quickmarks_file_path }}"
    src: "quickmarks.j2"
    owner: "{{ qutebrowser_user_name }}"
    group: "{{ qutebrowser_user_name }}"
    mode: '644'
    force: yes
  become: true
  become_user: root

